import React from 'react';
import { FileText, Copy, Check } from 'lucide-react';

export default function TranscriptEditor({ transcript = '', onChange }) {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(transcript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const wordCount = transcript ? transcript.trim().split(/\s+/).filter(Boolean).length : 0;
  const charCount = transcript ? transcript.length : 0;

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col h-full">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2 text-indigo-400">
          <FileText className="w-5 h-5" />
          <h3 className="font-bold text-slate-100 text-lg">Raw Speech Transcript</h3>
        </div>

        <div className="flex items-center gap-3">
          <span className="text-xs text-slate-400 font-mono">
            {wordCount} words | {charCount} chars
          </span>
          <button
            type="button"
            onClick={handleCopy}
            className="flex items-center gap-1.5 text-xs px-2.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition"
            title="Copy transcript"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy</span>
              </>
            )}
          </button>
        </div>
      </div>

      <p className="text-xs text-slate-400 mb-3">
        Below is the exact text generated by Whisper from the lecture recording. Review and make any necessary corrections before dispatch.
      </p>

      <div className="relative flex-1 min-h-[320px]">
        <textarea
          value={transcript}
          onChange={(e) => onChange(e.target.value)}
          placeholder="No raw transcript available..."
          className="w-full h-full min-h-[320px] bg-slate-950 border border-slate-800 rounded-xl p-4 text-sm font-sans text-slate-200 leading-relaxed focus:outline-none focus:ring-2 focus:ring-indigo-500/80 resize-y"
        />
      </div>
    </div>
  );
}
